FROM node:10

ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
ENV PATH=$PATH:/home/node/.npm-global/bin
ENV NPM_CONFIG_LOGLEVEL info

WORKDIR /home/node/app

COPY package*.json ./
RUN npm install

COPY . ./

EXPOSE 8000

RUN chown -R node:node /home/node/app

USER node

CMD ["npm", "start"]
